BOOKIE_CODES_AND_INDICES = {
    "B3": (0, "Bet365"),
    "SK": (1, "Sky Bet"),
    "LD": (2, "Ladbrokes"),
    "WH": (3, "William Hill"),
    "MR": (4, "Marathon Bet"),
    "FB": (5, "Betfair"),
    "VC": (6, "BETVICTOR"),
    "PP": (7, "Paddy Power"),
    "UN": (8, "UNIBET"),
    "CE": (9, "Coral"),
    "FR": (10, "BetFred"),
    "BY": (11, "BoyleSports"),
    "BX": (12, "ToteSport"),
    "BL": (13, "BLACKTYPE"),
    "PS": (14, "Bet Stars"),
    "WA": (15, "Betway"),
    "BB": (16, "Bet Bright"),
    "OE": (17, "10 Bet"),
    "SO": (18, "Sporting Bet"),
    "EB": (19, "188 Bet"),
    # "EE": (20, "888Sport"),
    # "PE": (21, "SportPesa"),
    "SX": (22, "Spread EX")
}

BOOKIE_NAME_TO_INDEX = {
    "Bet365": 0,
    "Sky Bet": 1,
    "Ladbrokes": 2,
    "William Hill": 3,
    "Marathon Bet": 4,
    "Betfair": 5,
    "Paddy Power": 6,
    "UNIBET": 7,
    "Coral": 8,
    "BetFred": 9,
    "BoyleSports": 10,
    "ToteSport": 11,
    "BLACKTYPE": 12,
    "Bet Stars": 13,
    "Betway": 14,
    "Bet Bright": 15,
    "10 Bet": 16,
    "Sporting Bet": 17,
    "188 Bet": 18,
    # "888Sport": 19,
    "BETVICTOR": 20,
    "SportPesa": 21,
    "Spread EX": 22
}